global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server1'
    static_configs:
      - targets: ['185.86.144.62:5050']

  - job_name: 'system1'
    static_configs:
      - targets: ['185.86.144.62:9100']

